name: Patrick van Beek
favicon: null
layout_spectrum: 0.5023974839132279
typography_spectrum: 0.49518176750279963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5317462787497789
  lightness: 0.5916820766869932
  saturation: 0.8219741641078144
  rhythmicContrast: 0.8482621356379241
purpose: []
